services:
  app:
    container_name: next-drizzle-auth
    build: .
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - node_modules/
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: ["npm", "run", "start"]
    restart: always
